### ISSUE TITLE
Can't run tools on Mac

### ISSUE THREAD

**Issue by topographos** [alexbruy/processing-whitebox#10]
Hi,
I am running QGIS 3 on Mac High Sierra and after downloading WBT and setting up the directory I get the below message when I run any of the tools:

/bin/sh: /Users/michal/Documents/WBT/: is a directory

Is there anything I missing ? 
Many thanks
Michal

**Comment by alexbruy** [comment]
You need to specify path to the WhiteBox Tools executable file `whitebox_tools`, not path to the directory.
