### ISSUE TITLE
Optional file inputs do not appear to be recognized

### ISSUE THREAD

**Issue by jblindsay** [alexbruy/processing-whitebox#14]
I received a '**Warning Missing Parameter Value**' error when running the CreateColourComposite tool because I did not specify the optional input opacity band file name. This parameter is marked as optional and should not be specified when it is not entered by the user. Does QGIS not allow for optional file parameters?

![image](https://user-images.githubusercontent.com/8441542/50609489-c3414600-0e9d-11e9-9113-38e9f0058760.png)

**Comment by alexbruy** [comment]
Fixed in 0.10.

**Comment by jblindsay** [comment]
I can't thank you enough Alex. This is wonderful. I think that the QGIS WhiteboxTools plugin is getting a lot of attention right now so having these issues resolved is wonderful timing.
