### ISSUE TITLE
Help files for tools

### ISSUE THREAD

**Issue by jblindsay** [alexbruy/processing-whitebox#16]
Hi Alex,
Do you know if there is a way to associate help files with the tools? I have been working on improving the documentation for each of the tools in the WhiteboxTools [user manual](https://jblindsay.github.io/wbt_book/preface.html) and this has resulted in high quality HTML based documentation. I assume that QGIS tools are essentially HTML files. Is there a folder in the plugin that could be added, that I can populate with tool documentation, to be associated with each of the plugin tools?

**Comment by jblindsay** [comment]
Hi Alex,
That's very kind; I didn't mean to make more work for you, which is why I thought that if it was just a matter of dumping some HTML files into a particular folder, that I could probably do that. I can certainly see your point about maintenance and the overall size of the plugin. In fact, this is one of the reasons that I did away with the pdf version of the user manual and created the online help instead. That and it's much easier to keep the help documentation up-to-date that way. Anyhow, if you need help with the linking tool help, please let me know. As always, I appreciate all your efforts on this front as the QGIS plugin hits a key target audience for WhiteboxTools.

**Comment by alexbruy** [comment]
Don't worry, this does not make more work. I enjoy doing it and making the plugin better. WhiteboxTools is really great toolset and having it available in QGIS extends its analysis functionality a lot. And with such cool documentation available users will find it even more easier to use.

**Comment by jblindsay** [comment]
Okay, well I'm thankful that you are able to link to the tool documentation. I agree that doing so will certainly help QGIS users to use the WhiteboxTools plugins more easily and that is a big bonus.

**Comment by alexbruy** [comment]
Fixed in 0.11
