### ISSUE TITLE
Minimum version too high for QGIS 2.99 Master

### ISSUE THREAD

**Issue by hareldunn** [alexbruy/processing-whitebox#2]
![image](https://user-images.githubusercontent.com/24369355/34328908-4ce6fa04-e8f6-11e7-86fa-588ae4473ae3.png)

**Comment by alexbruy** [comment]
There is nothing wrong with plugin, it was developed for QGIS 3.

**Comment by mstuyts** [comment]
QGIS 2.99 is the development version/release candidate for QGIS 3, so your plugin should work in QGIS 2.99.  Technically your metadata is correct, but if you want it to work in the current development version of QGIS, you should change the minimum version and add a maximum version.

`qgisMinimumVersion=2.99`
`qgisMaximumVersion=3.98`

**Comment by alexbruy** [comment]
Being QGIS core developer I perfectly understand its versioning scheme and release schedule. As well as which versions to use in plugin metadata.

**Comment by mstuyts** [comment]
I'm sorry, I misunderstood "it was developed for QGIS 3. QGIS 2.99 does not load pugins for QGIS 3." I thought you meant your plugin isn't meant to be used in QGIS 2.99. Apparently you mean QGIS does not interpret  `qgisMinimumVersion=3.0` correctly.

Thanks for this great plugin.
