### ISSUE TITLE
Batch processing interface won't separate input files into distinct rows

### ISSUE THREAD

**Issue by gsienkoPL** [alexbruy/processing-whitebox#20]
Issue exact the same as this one in [GIS.SE](https://gis.stackexchange.com/questions/301448/qgis-batch-processing-interface-wont-separate-input-files-into-distinct-rows?rq=1). 

When trying in the processing toolbox  select >1 input file, the batch processing dialog concatenates the inputs into a single row, separating each with a ";" rather than breaking them out into separate rows. This causes the tool to fail, as it expects a single input.

Observed in LidarTools.

**Comment by alexbruy** [comment]
Not reproducible with latest QGIS and plugin versions.

**Comment by gsienkoPL** [comment]
I was trying with the latest 3.6.1 and 3.4.6. Clean profile, added only latest plugin for WhitBox. Algorithm ClipLidarToPolygon. 

On 3.4.6 - I can select multiple files, but everything is in one row, separated by ;
On 3.6.1 - I cannot select multiple files.
