### ISSUE TITLE
"LidarJoin" - Incorrect parameter value for inputs

### ISSUE THREAD

**Issue by gsienkoPL** [alexbruy/processing-whitebox#21]
Tested on 3.4.6 and 3.6.1, clean profile, WhiteBox for Processing 0.11.1, WhiteBox 0.14.1. Algorythm LidarJoin. 

After selecting las files Qgis show error about incorrect parameter value for inputs.
[screenshot](https://user-images.githubusercontent.com/16090543/56266922-aef02480-60ed-11e9-8e28-444a616cc3b5.png)

**Comment by alexbruy** [comment]
Not a plugin issue
