### ISSUE TITLE
QGIS Installation Issue - Couldn't load plugin 'processing-whitebox-master' 

### ISSUE THREAD

**Issue by dawrightau** [alexbruy/processing-whitebox#23]
Hi Alex

Looking forward to using your plug-in for whiteboxtools but am not having any luck.

Below is the error message I get in QGIS. I have tried in  both QGIS 7.6 and 7.8

I have experimental plugs turned on in my plugin settings. Your plug-in isn't listed in the QGIS plug-in repository. Accordingly I have downloaded your zip file from https://github.com/alexbruy/processing-whitebox and in QGIS manage and install plug-ins I have tried installing from a zip file but get the error message below. I have also tried manually installing in the plug-ins folder and rebooting QGIS without luck.

Hopefully is something simple. Be grateful for any advice what I am doing wrong.

Much appreciated 

David

Installation Error Message:
```
Couldn't load plugin 'processing-whitebox-master' 

ModuleNotFoundError: No module named 'processing_whitebox' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:/Users/liveguest01/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing-whitebox-master\__init__.py", line 28, in 
    from processing_whitebox.whiteboxProviderPlugin import WhiteboxProviderPlugin
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'processing_whitebox'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.8.0-Zanzibar Zanzibar, 11aff65f10 

Python Path:
C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python
D:/Users/liveguest01/AppData/Roaming/QGIS/QGIS3\profiles\default/python
D:/Users/liveguest01/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.8\bin\python37.zip
C:\PROGRA~1\QGIS3~1.8\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib
C:\Program Files\QGIS 3.8\bin
C:\PROGRA~1\QGIS3~1.8\apps\Python37
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\Pythonwin
D:/Users/liveguest01/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

**Comment by alexbruy** [comment]
Don't use files from GitHub, unless you perfectly understand why you need them and how to use them. There is a **repository** with plugins, install them from it.

**Comment by dawrightau** [comment]
Alex thank you for your prompt reply.

The information I was missing, which I found by google searching and further trial and error over the past couple of hours since reading your response, is, that your repository first needs to be added as a plug-ins repository in addition to the core QGIS plug-in repository. While it is now obvious, I have only ever used the default plug-in repository for core or experimental plug-ins or downloaded and installed plugin-ins from zip files from third parties. I was unaware you could add other repositories like yours. 

I regret having wasted your time but for could I ask for those like me, that are not in the know about this possibility, it would be helpful if this missing piece of information was somewhere in the instructions for your repository including which url to paste when adding a repository. Your instructions on how to add your plug in starts after this step. While it is now obvious, I have spent hours trying to work out how to do something very simple. I am pleased to have got there and look forward to using your plugin and whiteboxtools.

I hope this is helpful feedback as you request on your site.

Thanks and regards

David

**Comment by jblindsay** [comment]
Please note that I've recently updated the [WhiteboxTools user manual](https://jblindsay.github.io/wbt_book/qgis_plugin.html) to include detailed instruction on how to install the plugin into QGIS. Hopefully this will help others discover this information as well.

**Comment by alexbruy** [comment]
@jblindsay I don't think there is a need in such instructions, as QGIS documentation already have big and detailed chapter about plugins and their management. This chapter covers all topics, including installation plugins from 3rd party repositories. The problem here is users who did not read documentation prior using the tool even when they have problems and were pointed to documentation containing all necessary information.
