### ISSUE TITLE
cannot load from repository in QGIS

### ISSUE THREAD

**Issue by saralizj** [alexbruy/processing-whitebox#25]
Hello there.  I've followed the instructions for loading the Whitebox QGIS plug-in to the letter, but when I search for the plug-in, I get nothing. I've connected to the repository.  Any ideas?  I'm using QGIS build 3.4.1.

Thanks!

**Comment by alexbruy** [comment]
Your QGIS is too old.

**Comment by saralizj** [comment]
How can 3.4.1 be too old?  It's the current long-term stable release.

**Comment by alexbruy** [comment]
After 3.4 there were 3.6, 3.8 and now there is 3.10. Not to mention master branch.
