### ISSUE TITLE
The repo link is broken

### ISSUE THREAD

**Issue by mismaielahmed** [alexbruy/processing-whitebox#29]
The Whitebox tools cannot be installed in QGIS because the repo link is broken (https://plugins.bruy.me/plugins/plugins.xml and https://plugins.bruy.me/processing-whitebox.html).
Can you please update the repo link? or add a method to install the Whitebox tool in QGIS offline without the need for the online repo?

**Comment by alexbruy** [comment]
Duplicates #28.

**Comment by mismaielahmed** [comment]
So, can you please mention the solution to this problem? it seems that everyone is having the same problem.
