### ISSUE TITLE
FYI might need to convert files to a format that whitebox_tools recognises

### ISSUE THREAD

**Issue by AlisterH** [alexbruy/processing-whitebox#3]
Hi,
This looks like a great addition to QGIS!
Perhaps I am mistaken, but I had an idea that Processing algorithms are supposed to automatically convert input files to an appropriate format for the tool being used e.g. importing files into a temporary Grass workspace to operate on them.
I see that some input layers will need conversion to be used by Whitebox:
````
****************************
* Welcome to AbsoluteValue *
****************************
Reading data...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: InvalidData, error: StringError("The BigTiff format is not currently supported.") }) }', src\libcore\result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by alexbruy** [comment]
TIF listed as supported format in the WhiteBox Tools documentation, so there is no need to convert anything.

Error message is coming from WhiteBox Tool and says

> The BigTiff format is not currently supported.

This simply means that BigTiff extension is not supported while file format itself is supported. IMHO this should be fixed upstream.
