### ISSUE TITLE
Watershedding Function from Snap Jenson PourPoints

### ISSUE THREAD

**Issue by erikafreeman** [alexbruy/processing-whitebox#30]
I have created a graphical modeller for the process of generating catchments from lakes. However, it fails at the Watershed function with this error: 

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/macros/mod.rs:15:40

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

I then tried the Watershed function outside of the the modeller and had the same error. 
Strangely, it works if called from python with the same inputs.

**Comment by erikafreeman** [comment]
![WhiteBoxInputs](https://user-images.githubusercontent.com/48226150/79757659-4ba65d00-8314-11ea-8dcb-4f799088e487.jpg)
![ERROR](https://user-images.githubusercontent.com/48226150/79757663-4cd78a00-8314-11ea-8b7f-9189bd7a5b59.jpg)

**Comment by erikafreeman** [comment]
here are the files I tried it with: https://github.com/erikafreeman/WhiteboxTest

**Comment by alexbruy** [comment]
Fixed in 1.0. Please note, you should remove previously installed versions of the plugin before installing version 1.0.
