### ISSUE TITLE
Installed version > disponible version

### ISSUE THREAD

**Issue by pedrogeo** [alexbruy/processing-whitebox#31]
Hi Alex,

I use Qgis 3.10 and I installed the plugin from your repository. 
![plugins_options](https://user-images.githubusercontent.com/12395408/80382874-229d4380-88a3-11ea-9a41-fb13ba413327.png)

But when I look at the Whitebox plugin in the plugins list, I see that the version installed (0.15) is superior than the version available (0.14) :
![plugins_list](https://user-images.githubusercontent.com/12395408/80383067-642dee80-88a3-11ea-8d41-226b1d5280a1.png)

I have no error message but when I go to Processing options to set the repository of Whitebox provider, I can't do anything :
![processing_options](https://user-images.githubusercontent.com/12395408/80383329-bb33c380-88a3-11ea-9000-01a9376fd74b.png)

So, all the algorithm are listed in Processing but they are not functional.

If someone has an idea ?

Pierre

**Comment by alexbruy** [comment]
Repository file was out of sync. Fixed now.

And please, don't add images to tickets without real need.

**Comment by pedrogeo** [comment]
Thanks Alex, sorry for the images but it was just to illustrate my problem.

Pierre
