### ISSUE TITLE
Option parameters are interpreted as ints

### ISSUE THREAD

**Issue by jblindsay** [alexbruy/processing-whitebox#7]
In running tools that contain option parameters, the command-line instruction interprets these parameters as integers (likely the list position) rather than the string. For example, running the LidarIdwInterpolation tool, I see the following command-line:

"C:/Users/John Lindsay/Documents/WBT/whitebox_tools.exe" --run=LidarIdwInterpolation --input="C:\Users\John Lindsay\Documents\Data\StudyData_no_oto.las" --parameter="0" --returns="0" --resolution=1.0 --weight=1.0 --radius=2.5 --exclude_cls="17" --minz=0.0 --maxz=9999.0 --output="C:\Users\John Lindsay\Documents\Data\tmp3.flt" -v

Here, the parameter and returns flags should be the strings 'elevation' and 'all' respectively. As a result tools that contain option parameters are not functioning correctly currently.

**Comment by alexbruy** [comment]
Fixed in 0.7.1
