### ISSUE TITLE
Installing Processing for Whitebox

### ISSUE THREAD

**Issue by afcp87** [alexbruy/processing-whitebox#8]
Hi, 

I am new to QGIS and wanted to ask the required steps for installing the processing for whitebox package. I am not sure if I am performing the correct steps but I first installed the package using the plugin menu. After installing I receive the following message (I can provide the full error message if needed):
```
Couldn't load plugin 'processing-whitebox-master' 
ModuleNotFoundError: No module named 'processing_whitebox' 
```
I have installed the Whitebox tools package. Any help would be appreciated. Thank you so much.

**Comment by alexbruy** [comment]
Looks like you used not plugin package, but copy of the repository. Please use Plugin Manager instead.

**Comment by afcp87** [comment]
I tried using plugin manager but couldn't find the plugin when searching.

**Comment by afcp87** [comment]
Nevermind, I found the issue. Thank you for the help!

**Comment by janzachar** [comment]
What was the exact procedure. I have the same problem. No plugin of Whitebox in Plugin manager and no chnace to install it via dawnloaded zip file from repository.
